### ISSUE TITLE
error[E0635]: unknown feature `proc_macro_span_shrink`

### ISSUE THREAD

**Issue by cacilhas** [TeXitoi/structopt#533]
```
  --> /home/cacilhas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.59/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |
```

Versions 0.2.18 until 0.3.26, stopped working in nightly 0.72.

**Comment by epage** [comment]
Try updating your version of `proc-macro2`

`cargo update -p proc-macro2`

However, see also #525
